{
 "title": "seeed-weather",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, temperature FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, humidity FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, pressure FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  },
  {
   "title": "Light Intensity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, light_intensity FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  },
  {
   "title": "Min Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, min_wind_direction FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  },
  {
   "title": "Heating Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "dataset": "SEEED_WEATHER",
     "rawSql": "SELECT time, heating_temperature FROM SEEED_WEATHER.mqtt_data GROUP BY time"
    }
   ]
  }
 ]
}